default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "prompter_development") %>

test:
  <<: *default
  database: prompter_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "prompter_production") %>
